### ISSUE TITLE
Using property element syntax after children causes ParseException.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#114]
Consider the main window in the [Avalonia control catalog](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainWindow.xaml):

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:pages="clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Avalonia Control Gallery"
        Icon="resm:ControlCatalog.Assets.test_icon.ico?assembly=ControlCatalog">
  <TabControl Classes="sidebar">
    <TabControl.Transition>
      <CrossFade Duration="0.25"/>
    </TabControl.Transition>
    <TabItem Header="Border"><pages:BorderPage/></TabItem>
    <TabItem Header="Button"><pages:ButtonPage/></TabItem>
    <TabItem Header="Canvas"><pages:CanvasPage/></TabItem>
    <TabItem Header="Carousel"><pages:CarouselPage/></TabItem>
    <TabItem Header="CheckBox"><pages:CheckBoxPage/></TabItem>
    <TabItem Header="DropDown"><pages:DropDownPage/></TabItem>
    <TabItem Header="Expander"><pages:ExpanderPage/></TabItem>
    <TabItem Header="Image"><pages:ImagePage/></TabItem>
    <TabItem Header="LayoutTransformControl"><pages:LayoutTransformControlPage/></TabItem>
    <TabItem Header="Menu"><pages:MenuPage/></TabItem>
    <TabItem Header="RadioButton"><pages:RadioButtonPage/></TabItem>
    <TabItem Header="Slider"><pages:SliderPage/></TabItem>
    <TabItem Header="TextBox"><pages:TextBoxPage/></TabItem>
    <TabItem Header="ToolTip"><pages:ToolTipPage/></TabItem>
    <TabItem Header="TreeView"><pages:TreeViewPage/></TabItem>
  </TabControl>
</Window>
```

If I move the `TabControl.Transition` element to after the children, it should work:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:pages="clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Avalonia Control Gallery"
        Icon="resm:ControlCatalog.Assets.test_icon.ico?assembly=ControlCatalog">
  <TabControl Classes="sidebar">
    <TabItem Header="Border"><pages:BorderPage/></TabItem>
    <TabItem Header="Button"><pages:ButtonPage/></TabItem>
    <TabItem Header="Canvas"><pages:CanvasPage/></TabItem>
    <TabItem Header="Carousel"><pages:CarouselPage/></TabItem>
    <TabItem Header="CheckBox"><pages:CheckBoxPage/></TabItem>
    <TabItem Header="DropDown"><pages:DropDownPage/></TabItem>
    <TabItem Header="Expander"><pages:ExpanderPage/></TabItem>
    <TabItem Header="Image"><pages:ImagePage/></TabItem>
    <TabItem Header="LayoutTransformControl"><pages:LayoutTransformControlPage/></TabItem>
    <TabItem Header="Menu"><pages:MenuPage/></TabItem>
    <TabItem Header="RadioButton"><pages:RadioButtonPage/></TabItem>
    <TabItem Header="Slider"><pages:SliderPage/></TabItem>
    <TabItem Header="TextBox"><pages:TextBoxPage/></TabItem>
    <TabItem Header="ToolTip"><pages:ToolTipPage/></TabItem>
    <TabItem Header="TreeView"><pages:TreeViewPage/></TabItem>
    <TabControl.Transition>
      <CrossFade Duration="0.25"/>
    </TabControl.Transition>
  </TabControl>
</Window>
```

However it doesn't - I get the exception:

```
OmniXaml.LoadException: Error loading XAML: OmniXaml.ParseException: The root should be an element.
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.AssertValidElement() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 153
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 205
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 140
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 78
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 58
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 226
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 140
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 78
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 58
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 226
   at OmniXaml.Parsers.Parser.InstructionParser.SetNextInstruction() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 225
   at OmniXaml.Parsers.Parser.InstructionParser.SkipTextNodes() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 79
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 71
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 237
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 207
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 123
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 63
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 212
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 123
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 63
   at OmniXaml.Parsers.Parser.InstructionParser.<Parse>d__23.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 45
   at OmniXaml.MemberDependencyNodeSorter.<Sort>d__11.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\MemberDependencyNodeSorter.cs:line 25
   at OmniXaml.XmlParser.Parse(IEnumerable`1 xamlNodes) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlParser.cs:line 32
   at OmniXaml.XmlParser.Parse(IXmlReader stream) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlParser.cs:line 27
   at OmniXaml.XmlLoader.Load(Stream stream, IParser parser) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlLoader.cs:line 29 ---> OmniXaml.ParseException: The root should be an element.
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.AssertValidElement() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 153
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 205
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 140
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 78
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 58
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 226
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseChildren>d__16.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 140
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseNestedElements>d__10.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 78
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseExpandedElement>d__9.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 58
   at OmniXaml.Parsers.ProtoParser.ProtoInstructionParser.<ParseElement>d__22.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\ProtoParser\ProtoInstructionParser.cs:line 226
   at OmniXaml.Parsers.Parser.InstructionParser.SetNextInstruction() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 225
   at OmniXaml.Parsers.Parser.InstructionParser.SkipTextNodes() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 79
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 71
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 237
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 207
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 123
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 63
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 212
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 123
   at OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 63
   at OmniXaml.Parsers.Parser.InstructionParser.<Parse>d__23.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\Parsers\Parser\InstructionParser.cs:line 45
   at OmniXaml.MemberDependencyNodeSorter.<Sort>d__11.MoveNext() in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\MemberDependencyNodeSorter.cs:line 25
   at OmniXaml.XmlParser.Parse(IEnumerable`1 xamlNodes) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlParser.cs:line 32
   at OmniXaml.XmlParser.Parse(IXmlReader stream) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlParser.cs:line 27
   at OmniXaml.XmlLoader.Load(Stream stream, IParser parser) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlLoader.cs:line 29
   --- End of inner exception stack trace ---
   at OmniXaml.XmlLoader.Load(Stream stream, IParser parser) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlLoader.cs:line 33
   at OmniXaml.XmlLoader.Load(Stream stream, Settings loadSettings) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\OmniXAML\Source\OmniXaml\XmlLoader.cs:line 21
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Object rootInstance, Uri uri) in D:\projects\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 173
   at Avalonia.DesignerSupport.DesignerAssist.UpdateXaml2(Dictionary`2 dic) in D:\projects\Avalonia\src\Avalonia.DesignerSupport\DesignerAssist.cs:line 102
   at Avalonia.Designer.AppHost.AvaloniaAppHost.XamlUpdater()
```

**Comment by SuperJMN** [comment]
It should work fine with OX2 :)
