### ISSUE TITLE
Crash with DataTemplate in Perspex

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#38]
If I run XamlTestApplication in the `xaml-datatemplates` branch of Perspex and go to the "Lists" tab, i get the following exception:

```
System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Perspex.Markup.Xaml
  StackTrace:
       at Glass.StackingLinkedList`1.get_CurrentValue() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\Glass\StackingLinkedList.cs:line 18
  InnerException: 
```

Interestingly in the designer I get a different error:

```
System.ArgumentException: Object of type 'Perspex.Controls.TextBlock' cannot be converted to type 'Perspex.Markup.Xaml.Templates.TemplateContent'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OmniXaml.Typing.MemberValuePlugin.SetValueIndependent(Object instance, Object value) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\Typing\MemberValuePlugin.cs:line 32
   at OmniXaml.Typing.MemberValuePlugin.SetValue(Object instance, Object value) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\Typing\MemberValuePlugin.cs:line 21
   at Perspex.Markup.Xaml.Context.PerspexXamlMemberValuePlugin.SetValue(Object instance, Object value) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\Context\PerspexXamlMemberValuePlugin.cs:line 46
   at OmniXaml.Typing.MutableXamlMember.SetValue(Object instance, Object value) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\Typing\MutableXamlMember.cs:line 56
   at OmniXaml.ObjectAssembler.StateCommuter.AssignChildToParentProperty() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\StateCommuter.cs:line 62
   at OmniXaml.ObjectAssembler.StateCommuter.AssociateCurrentInstanceToParent() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\StateCommuter.cs:line 161
   at OmniXaml.ObjectAssembler.StateCommuter.AssociateCurrentInstanceToParentRightAfterCreation() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\StateCommuter.cs:line 223
   at OmniXaml.ObjectAssembler.Commands.StartMemberCommand.ForceInstanceCreationOfCurrentTypeAndAssociateIfPossible() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\Commands\StartMemberCommand.cs:line 61
   at OmniXaml.ObjectAssembler.Commands.StartMemberCommand.Execute() in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\Commands\StartMemberCommand.cs:line 52
   at OmniXaml.ObjectAssembler.ObjectAssembler.Process(XamlInstruction instruction) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\ObjectAssembler\ObjectAssembler.cs:line 70
   at OmniXaml.XamlXmlParser.Parse(IEnumerable`1 xamlNodes) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\XamlXmlParser.cs:line 33
   at OmniXaml.XamlXmlParser.Parse(Stream stream) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\XamlXmlParser.cs:line 28
   at OmniXaml.XamlLoader.Load(Stream stream) in D:\projects\Perspex\src\Markup\Perspex.Markup.Xaml\OmniXAML\Source\OmniXaml\XamlLoader.cs:line 16
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Perspex.Designer.AppHost.PerspexAppHost.<>c__DisplayClass17_0.<DoInit>b__2(Stream stream)
   at Perspex.Designer.AppHost.PerspexAppHost.XamlUpdater()
```

I'm not sure if it's something I'm doing wrong or not.

**Comment by SuperJMN** [comment]
I'm digging into it. This is specially annoying for me.

**Comment by SuperJMN** [comment]
The problem for what I know is the XAML you had a DataTemplate with 2 elements and no parent. You should put the children on a "container", like a Grid, Stack Panel...

**Comment by grokys** [comment]
OK, filed a bug for a better exception to be thrown: #39 ;)
